import type { ReactNode } from "react";
import { Link } from "wouter";
import { useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, GitBranch, Lock, Menu, Play, Sparkles, X } from "lucide-react";
import { WORKSPACE_NAV_TABS, WORKSPACE_TAB_META, projectPath, type WorkspaceTab } from "@/lib/nav";
import { cn } from "@/lib/utils";
import type { ProjectRef } from "@/types/workspace";
import { Badge } from "@/components/ui/badge";
import { useOptionalWorkspace } from "@/features/workspace/context";
import { SkipLink } from "./app-shell";
import { OfflineBanner } from "./offline-banner";

export function WorkspaceShell({ project, branch, tab, onBranchClick, gitBadge, children }: { project: ProjectRef; branch: string; tab: WorkspaceTab; onBranchClick?: () => void; gitBadge?: number; children: ReactNode }) {
  const ws = useOptionalWorkspace();
  const [open, setOpen] = useState(false);
  const badge = gitBadge ?? (ws ? ws.changes.length : 0);
  return <div className="studio-grid flex h-dvh flex-col overflow-hidden bg-background md:pl-64">
    {open ? <button type="button" aria-label="Close workspace navigation" className="fixed inset-0 z-40 bg-slate-950/60 backdrop-blur-sm md:hidden" onClick={() => setOpen(false)} /> : null}
    <aside className={cn("fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r border-white/10 bg-sidebar/95 shadow-2xl shadow-black/20 backdrop-blur-xl transition-transform md:translate-x-0", open ? "translate-x-0" : "-translate-x-full")} aria-label="Workspace navigation">
      <div className="flex h-16 items-center justify-between border-b border-white/10 px-4"><Link href="/app" aria-label="Back to Chrono home" className="text-sm font-semibold text-white">Chrono <span className="font-normal text-sidebar-muted">/ Studio</span></Link><button type="button" className="grid size-9 place-items-center rounded-lg text-sidebar-muted hover:bg-white/10 hover:text-white md:hidden" aria-label="Close workspace navigation" onClick={() => setOpen(false)}><X className="size-5" /></button></div>
      <div className="border-b border-white/10 px-4 py-4"><p className="truncate text-sm font-semibold text-white">{project.name}</p><p className="mt-1 truncate font-mono text-[11px] text-sidebar-muted">{project.owner}/{project.name}</p></div>
      <nav className="space-y-1 px-3 py-5" aria-label="Workspace"><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-sidebar-muted">Project</p>{WORKSPACE_NAV_TABS.map((t) => { const meta = WORKSPACE_TAB_META[t]; const active = t === tab; return <Link key={t} href={projectPath(project.owner, project.name, t)} onClick={() => setOpen(false)} aria-current={active ? "page" : undefined} data-testid={`tab-${t}`} className={cn("group flex h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition", active ? "bg-primary/15 text-primary shadow-[inset_3px_0_0_hsl(var(--primary))]" : "text-sidebar-muted hover:bg-white/7 hover:text-white")}><span className={cn("grid size-7 place-items-center rounded-lg", active ? "bg-primary/15" : "bg-white/5 group-hover:bg-white/10")}><meta.icon className="size-4" aria-hidden /></span>{meta.label}{t === "git" && badge > 0 ? <span data-testid="badge-changes" className="ml-auto rounded-full bg-primary px-2 py-0.5 text-[10px] font-semibold text-primary-foreground">{badge > 99 ? "99+" : badge}</span> : null}</Link>; })}</nav>
      <div className="mt-auto border-t border-white/10 p-3"><Link href={projectPath(project.owner, project.name, "ai")} className="flex items-center gap-2 rounded-xl border border-primary/25 bg-primary/10 p-3 text-xs font-semibold text-primary hover:bg-primary/15"><Sparkles className="size-4" aria-hidden /> Ask Chrono <ChevronRight className="ml-auto size-3.5" aria-hidden /></Link></div>
    </aside>
    <nav aria-label="Accessibility links"><SkipLink /></nav>
    <header className="z-30 shrink-0 border-b border-border/70 bg-background/85 pt-safe backdrop-blur-xl"><OfflineBanner /><div className="mx-auto flex h-16 w-full max-w-6xl items-center gap-2 px-3 sm:px-5"><button type="button" onClick={() => setOpen(true)} aria-label="Open workspace navigation" data-testid="button-toggle-workspace-sidebar" className="grid size-10 place-items-center rounded-xl border border-border bg-surface text-muted-foreground hover:text-foreground md:hidden"><Menu className="size-5" /></button><Link href="/app/projects" aria-label="Back to projects" className="grid size-10 place-items-center rounded-xl text-muted-foreground hover:bg-surface-2 hover:text-foreground"><ChevronLeft className="size-5" /></Link><div className="min-w-0 flex-1"><Link href={projectPath(project.owner, project.name, "overview")} aria-current={tab === "overview" ? "page" : undefined} aria-label={`${project.owner}/${project.name} — project overview`} className="flex max-w-full items-center gap-1 truncate text-sm font-semibold hover:text-primary" data-testid="link-overview"><span data-testid="text-repo-name" className="truncate"><span className="text-muted-foreground">{project.owner}/</span>{project.name}</span><ChevronRight className="size-3.5 shrink-0 text-muted-foreground" aria-hidden /></Link>{onBranchClick ? <button type="button" onClick={onBranchClick} data-testid="button-branch" className="-mx-1 flex max-w-full items-center gap-1 rounded px-1 py-0.5 font-mono text-[11px] text-muted-foreground hover:bg-surface-2 hover:text-foreground"><GitBranch className="size-3 shrink-0" aria-hidden /><span className="truncate" data-testid="text-branch">{branch}</span><ChevronDown className="size-3 shrink-0" aria-hidden /></button> : <p className="flex items-center gap-1 font-mono text-[11px] text-muted-foreground" data-testid="text-branch"><GitBranch className="size-3" aria-hidden /> {branch}</p>}</div><div className="hidden items-center gap-2 sm:flex"><span className="flex items-center gap-1.5 rounded-full border border-primary/20 bg-primary/10 px-2.5 py-1 text-[10px] font-semibold text-primary"><span className="size-1.5 rounded-full bg-primary" /> Ready</span>{project.source === "demo" ? <Badge tone="warning">Demo</Badge> : project.visibility === "private" ? <Badge><Lock className="size-3" aria-hidden /> Private</Badge> : null}</div>{tab !== "preview" ? <Link href={projectPath(project.owner, project.name, "preview")} data-testid="button-header-preview" className="inline-flex h-10 items-center gap-1.5 rounded-xl bg-primary px-3 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/15 transition hover:-translate-y-0.5 hover:bg-primary/90"><Play className="size-3.5 fill-current" aria-hidden /> Preview</Link> : null}</div></header>
    <main id="main" tabIndex={-1} className="mx-auto flex min-h-0 w-full max-w-6xl flex-1 flex-col overflow-y-auto bg-background/50 outline-none">{children}</main>
  </div>;
}
